name: "ci_build_and_test"

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Install libraries required by glfw
      run: sudo apt-get update && sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev mesa-common-dev

#    - name: Setup interactive tmate session
#      uses: mxschmitt/action-tmate@v3

    - name: Full build and test
      run: |
        mkdir build
        cd build
        cmake ..
        make -j 4
        
